language: node_js

node_js:
  - "0.10"
  - "4"

matrix:
  allow_failures:
   - node_js: "4"

services:
  - mongodb
  - rabbitmq

env:
  global:
    - secure: "tNNNVDWyepo9eYsZXADfwuj4MmXPbBg1cCF72AbVK4/aCVlXo+8lgLuObbeVuY4PUzCnP74fp1t9zliVr06IoyzUYqf6N/Fkgm3jnPlJnoOdYuJ3ap8t0SlMrGvoRIJjw1yN2WoDo2bY8FKseeRnhZE8G8G8qLoqKGH9iKEGrcMg8jUepyfY6bH9dZBV6NsTEQW9ewojTMnagDWGtq04OK9Flc+R2OzYrMp6mHfxHyIB8hKdeQtFouIdY0wgfzlZLiWI4Ltb8Lq2I0gM4tlubeoShdGRssitcxNjysBtg1ZndVGCn4Mh2BO31oQUsCD7ngzPNOc+d3YvQgLzfFfjJU3QetZmuKAlo4MzbrD1GkODlggvM4cA5Yij7tYXfI00xOqjbmua/pngjhXTkcW6KlylRri01mla4dQXYABA8Y3+P2f6E5+vABkUrKwygXAhaMUWmU8mEtv9YA6U/Iu9aM8rI0+FhuMbGpIq+o28hWAYm3SX57n4bNs+p5yfntCjzaHFaePnyKSmPKJPl+I3JsnS+2fAhYqUgGBVzipBOPkMOJGMSZN9xRAvEFkLSMrjI1MhFtOYwckHvegAIOmD1hutBTcuvqhY0n2hRL+uufgNKyAEKvWBmywhD9nUTDXXOxUEaWFz/FSXIX4fB0hxv1GdCm6G/N1Co8wiWISMGlg="

after_success:
 - ./node_modules/.bin/istanbul cover -x "**/spec/**" ./node_modules/.bin/_mocha --report lcovonly -- $(find spec -name '*-spec.js') -R spec --require spec/helper.js
 - cat ./coverage/lcov.info | node_modules/.bin/coveralls
 - chmod 755 ./build_children.sh
 - ./build_children.sh

notifications:
  slack:
    rooms:
    - secure: "DZ+r6cHd9kzKl0BoW2MmLnLhyPNivsjYWyRqVwjYtwNnsMZFSfQ13B6gojEw28PJmVqDu6am/bOhwD6gka8xuu5Fu7In0LMpdL4aNmV6bg/8B8CooYFG+izaa/9Cjsk9t9RG8oZggqXl/U1g4FGweczjU6UC/8WUU/QFsud1GXDZtdLm/80i+/CC1pmhKx73zcgXNWj/j4YDhTY1r3rsEM4nk5m2/CvSo9nYLY4VvTxlH1uA3OVKqDdoMPP8nX6N12qIBYJceDI8uXrBPKFfP+y6V7paq5VNIxAFYxEKkB9AUnNENgPSKvsTP0RWicstYbFosbJHw4o09e/+sui8Mj0UuK4eRfyBdTuj1/kSeUTIYCBffVLXtN5o/Hsm88Ak1Dd7gczQBXMlNQl7nXR9g38m150AMyinvyx52ZdOXiBhPRBbF9riD2fCgjxoCq8W3cVmRaU25lI/YyAMDUGaaVBVjRJCuMEMnFlXJdV2pGPIglRuPrB6llGnyCwTPNlPdsvVjWzQ6j9gV7jQb2mVvjo4c8Lvs0KI0UEAVrysWaslYd1Wgdh8HGSlPJua9Xpo7rQs5wsRqSqFwIZ038NCXWvXtZc828//KvWC+1e26puQfIjwMR/y6cqzF09h7+GkSePxYxoCqbNgSZ/u6KrOx0FOe+E4BrLl5PEtO3Y2iAg="
    on_success: never
    on_failure: always
    on_start: never

